apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency-webhook.fullname" . }}
  labels:
    {{- include "dependency-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "dependency-webhook.selectorLabels" . | nindent 4 }}
