apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency-controller.webhook.fullname" . }}
  labels:
    {{- include "dependency-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.port }}
      protocol: TCP
      name: https
      {{- if and (eq .Values.webhook.service.type "NodePort") .Values.webhook.service.nodePort }}
      nodePort: {{ .Values.webhook.service.nodePort }}
      {{- end }}
  selector:
    {{- include "dependency-controller.webhook.selectorLabels" . | nindent 4 }}
