//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIExportReference) DeepCopyInto(out *APIExportReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIExportReference.
func (in *APIExportReference) DeepCopy() *APIExportReference {
	if in == nil {
		return nil
	}
	out := new(APIExportReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyRule) DeepCopyInto(out *DependencyRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyRule.
func (in *DependencyRule) DeepCopy() *DependencyRule {
	if in == nil {
		return nil
	}
	out := new(DependencyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependencyRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyRuleList) DeepCopyInto(out *DependencyRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DependencyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyRuleList.
func (in *DependencyRuleList) DeepCopy() *DependencyRuleList {
	if in == nil {
		return nil
	}
	out := new(DependencyRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependencyRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyRuleSpec) DeepCopyInto(out *DependencyRuleSpec) {
	*out = *in
	out.Dependent = in.Dependent
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]DependencyTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyRuleSpec.
func (in *DependencyRuleSpec) DeepCopy() *DependencyRuleSpec {
	if in == nil {
		return nil
	}
	out := new(DependencyRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyTarget) DeepCopyInto(out *DependencyTarget) {
	*out = *in
	out.APIExportRef = in.APIExportRef
	out.FieldRef = in.FieldRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyTarget.
func (in *DependencyTarget) DeepCopy() *DependencyTarget {
	if in == nil {
		return nil
	}
	out := new(DependencyTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependentRef) DeepCopyInto(out *DependentRef) {
	*out = *in
	out.APIExportRef = in.APIExportRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependentRef.
func (in *DependentRef) DeepCopy() *DependentRef {
	if in == nil {
		return nil
	}
	out := new(DependentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldReference) DeepCopyInto(out *FieldReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldReference.
func (in *FieldReference) DeepCopy() *FieldReference {
	if in == nil {
		return nil
	}
	out := new(FieldReference)
	in.DeepCopyInto(out)
	return out
}
