apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  name: dependencies.opendefense.cloud
spec:
  permissionClaims:
    - group: "admissionregistration.k8s.io"
      resource: "validatingwebhookconfigurations"
      verbs: ["get", "list", "watch", "create", "update", "delete"]
  resources:
  - group: dependencies.opendefense.cloud
    name: dependencyrules
    schema: v260410-d7832fa.dependencyrules.dependencies.opendefense.cloud
    storage:
      crd: {}
status: {}
