apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apiresourceschema-dependencies.dependencies.opendefense.cloud.yaml
  - apiresourceschema-dependencyrules.dependencies.opendefense.cloud.yaml
  - apiexport-dependencies.opendefense.cloud.yaml
